Demo.PL/Controllers/RoleController.cs
using Demo.BLL.DTOS.Employees;
using Demo.DAL.Entities.Identity;
using Demo.PL.ViewModels.Employee;
using Demo.PL.ViewModels.Role;
using Demo.PL.ViewModels.User;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;

namespace Demo.PL.Controllers
{

    [Authorize(Roles = "Admin")]
    public class RoleController : Controller
    {
        private readonly RoleManager<IdentityRole> _userRole;
        private readonly UserManager<ApplicationUser> _userManager;

        public RoleController(RoleManager<IdentityRole> roleManager, UserManager<ApplicationUser> userManager)
        {
            _userRole = roleManager;
            _userManager = userManager;
        }

        #region Index
        [HttpGet]
        public async Task<IActionResult> Index()
        {
            var roles = _userRole.Roles.AsQueryable();
            var rolesVm = await roles.Select(u => new RoleViewModel
            {   
                Name = u.Name,
                Id = u.Id

            }).ToListAsync();




            return View(rolesVm);
        }
        #endregion

        #region Edit Get
        [HttpGet]
        public async Task<IActionResult> Edit(string? id)
        {
            if (id is null)
                return BadRequest();

            try
            {
                var role = await _userRole.FindByIdAsync(id);
                var users = await _userManager.Users.ToListAsync();



                return role == null ? NotFound() : View(new RoleViewModel
                {
                    Name = role.Name,
                    Id = role.Id,
                    users = users.Select(User => new UserRoleViewModel
                    {
                        UserName = User.UserName,
                        UserId = User.Id,
                        IsSelected = _userManager.IsInRoleAsync(User, role.Name).Result
                    }).ToList()
                });
            }
            catch (Exception ex)
            {
                return RedirectToAction("Index");
            }

        }
        #endregion

        #region Edit Post
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(RoleViewModel roleVm)
        {

            if (!ModelState.IsValid)
            {

                return View(roleVm);
            }

            try
            {
                if (roleVm.Id == null || roleVm is null)
                {
                    ModelState.AddModelError(string.Empty, "Failed to update Role.");
                    return View(roleVm);
                }
                else
                {
                    var role = await _userRole.FindByIdAsync(roleVm.Id);

                    if (role is null)
                    {
                        ModelState.AddModelError(string.Empty, "Failed to update role.");
                        return View(role);
                    }
                    else
                    {
                        role.Name = roleVm.Name;
                        var result = await _userRole.UpdateAsync(role);

                        foreach(var userRole in roleVm.users)
                        {
                            var user = await _userManager.FindByIdAsync(userRole.UserId);
                            if (userRole.IsSelected && !await _userManager.IsInRoleAsync(user, role.Name))
                            {
                                await _userManager.AddToRoleAsync(user, role.Name);
                            }
                            else if (!userRole.IsSelected && await _userManager.IsInRoleAsync(user, role.Name))
                            {
                                await _userManager.RemoveFromRoleAsync(user, role.Name);
                            }
                        }


                        if (result.Succeeded)
                        {
                            return RedirectToAction("Index");
                        }
                        else
                        {
                            foreach (var error in result.Errors)
                            {
                                ModelState.AddModelError(string.Empty, error.Description);
                            }

                        }
                    }
                }

                ModelState.AddModelError(string.Empty, "Failed to update roleVm.");
                return View(roleVm);
            }
            catch (Exception ex)
            {

                return View("Error", "An error occurred while updating the roleVm.");
            }
        }
        #endregion


        #region Details
        [HttpGet]
        public async Task<IActionResult> Details(string? id)
        {
            if (id is null)
                return BadRequest();

            var role = await _userRole.FindByIdAsync(id);
            var roleVm = new RoleViewModel
            {
                Name = role.Name,
                Id = role.Id
            };
            return roleVm == null ? NotFound() : View(roleVm);
        }
        #endregion


        #region Delete GEt
        [HttpGet]
        public async Task<IActionResult> Delete(string? id)
        {
            if (id is null)
                return BadRequest();

            var role = await _userRole.FindByIdAsync(id);
            if (role is not null)
            {

                var roleVm = new RoleViewModel
                {
                    Name = role.Name,
                    Id = role.Id,
                };
                return roleVm == null ? NotFound() : View(roleVm);


            }
            return View("Error", "An error occurred while deleting the roleVm.");

        }
        #endregion


        #region Delete Post
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Delete(RoleViewModel roleVm)
        {
            try
            {
                var role = await _userRole.FindByIdAsync(roleVm.Id);
                if (role is null)
                {
                    ModelState.AddModelError(string.Empty, "Failed to delete role.");
                    return View("Index");
                }
                else if (role is not null)
                {
                    var result = await _userRole.DeleteAsync(role);

                    if (result.Succeeded)
                    {
                        TempData["Message"] = "role deleted successfully!";
                        return RedirectToAction("Index");
                    }
                    return View(role);
                }

                ModelState.AddModelError(string.Empty, "Failed to delete role.");
                return View("Index");
            }
            catch (Exception ex)
            {
                return View("Error", "An error occurred while deleting the role.");
            }
        }
        #endregion


        #region SearchRoles
        [HttpGet]
        public async Task<IActionResult> SearchRoles(string searchValue)
        {

            var role = _userRole.Roles.AsQueryable();


            if (!string.IsNullOrWhiteSpace(searchValue))
            {
                searchValue = searchValue.ToLower();
                role = role
                    .Where(e => e.Name.ToLower().Contains(searchValue));
            }
            var usersVm = await role.Select(u => new RoleViewModel
            {
                Name = u.Name,
                Id = u.Id,
            }).ToListAsync();

            return PartialView("~/Views/Role/Partials/_RoleTablePartial.cshtml", usersVm);

        }
        #endregion


        #region CREATE

        [HttpGet]
        public IActionResult Create() => View();

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(RoleViewModel roleViewModel)
        {
            if (!ModelState.IsValid)
            {

                return View(roleViewModel);
            }

            try
            {
                var role = new IdentityRole
                {
                    Name = roleViewModel.Name,
                };
                var result = await _userRole.CreateAsync(role);

                if (result.Succeeded)
                {
                    TempData["Message"] = "Role created successfully!";
                    return RedirectToAction("Index");
                }


                ModelState.AddModelError(string.Empty, "Failed to create role.");
                return View(roleViewModel);
            }
            catch (Exception ex)
            {

                return View("Error", "An error occurred while creating the roleViewModel.");
            }
        }
        #endregion
    }
}

Demo.PL/Controllers/UserController.cs
using Demo.BLL.DTOS.Employees;
using Demo.DAL.Entities.Identity;
using Demo.PL.ViewModels.Employee;
using Demo.PL.ViewModels.Role;
using Demo.PL.ViewModels.User;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;

namespace Demo.PL.Controllers
{

    [Authorize(Roles = "Admin")]

    public class UserController : Controller
    {
        private readonly UserManager<ApplicationUser> _userManager;

        public UserController(UserManager<ApplicationUser> userManager)
        {
            _userManager = userManager;
        }

        #region Index
        [HttpGet]
        public async Task<IActionResult> Index()
        {
            var users = await _userManager.Users.ToListAsync();

            var usersVm = new List<UsersViewModel>();

            foreach (var user in users)
            {
                var roles = await _userManager.GetRolesAsync(user);

                usersVm.Add(new UsersViewModel
                {
                    Id = user.Id,
                    Email = user.Email,
                    FName = user.FName,
                    LName = user.LName,
                    Roles = roles.ToList() // Assicurati che sia una lista di stringhe
                });
            }

            return View(usersVm);
        }


        #endregion

        #region Edit Get
        [HttpGet]
        public async Task<IActionResult> Edit(string? id)
        {
            if (id is null)
                return BadRequest();

            try
            {
                var user = await _userManager.FindByIdAsync(id);


                var userVm = new UsersViewModel
                {
                    Email = user.Email,
                    FName = user.FName,
                    LName = user.LName,
                    Id = user.Id
                };


                return userVm == null ? NotFound() : View(userVm);
            }
            catch (Exception ex)
            {
                return RedirectToAction("Index");
            }

        } 
        #endregion

        #region Edit Post
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(UsersViewModel userVm)
        {

            if (!ModelState.IsValid)
            {

                return View(userVm);
            }

            try
            {
                if (userVm.Id == null || userVm is null)
                {
                    ModelState.AddModelError(string.Empty, "Failed to update employee.");
                    return View(userVm);
                }
                else
                {
                    var user = await _userManager.FindByIdAsync(userVm.Id);

                    if (user is null)
                    {
                        ModelState.AddModelError(string.Empty, "Failed to update employee.");
                        return View(userVm);
                    }
                    else
                    {
                        user.FName = userVm.FName;
                        user.LName = userVm.LName;
                        user.UserName = userVm.Email;
                        var result = await _userManager.UpdateAsync(user);
                        if (result.Succeeded)
                        {
                            return RedirectToAction("Index");
                        }
                        else
                        {
                            foreach (var error in result.Errors)
                            {
                                ModelState.AddModelError(string.Empty, error.Description);
                            }

                        }
                    }
                }

                ModelState.AddModelError(string.Empty, "Failed to update employee.");
                return View(userVm);
            }
            catch (Exception ex)
            {

                return View("Error", "An error occurred while updating the employee.");
            }
        } 
        #endregion


        #region Details
        [HttpGet]
        public async Task<IActionResult> Details(string? id)
        {
            if (id is null)
                return BadRequest();

            var users = await _userManager.FindByIdAsync(id);
            var user = new UsersViewModel
            {
                Email = users.Email,
                FName = users.FName,
                LName = users.LName,
                Id = users.Id
            };
            return users == null ? NotFound() : View(user);
        }
        #endregion


        #region Delete GEt
        [HttpGet]
        public async Task<IActionResult> Delete(string? id)
        {
            if (id is null)
                return BadRequest();

            var user = await _userManager.FindByIdAsync(id);
            if (user is not null)
            {

                var userVm = new UsersViewModel
                {
                    Email = user.Email,
                    FName = user.FName,
                    LName = user.LName,
                    Id = user.Id
                };
                return userVm == null ? NotFound() : View(userVm);


            }
            else
            {
                return View("Error", "An error occurred while deleting the employee.");
            }
            return View();
        } 
        #endregion


        #region Delete Post
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Delete(UsersViewModel userVm)
        {
            try
            {
                var user = await _userManager.FindByIdAsync(userVm.Id);
                if (user is null)
                {
                    ModelState.AddModelError(string.Empty, "Failed to delete employee.");
                    return View("Index");
                }
                else if (user is not null)
                {
                    var result = await _userManager.DeleteAsync(user);

                    if (result.Succeeded)
                    {
                        TempData["Message"] = "Employee deleted successfully!";
                        return RedirectToAction("Index");
                    }
                    return View(user);
                }

                ModelState.AddModelError(string.Empty, "Failed to delete employee.");
                return View("Index");
            }
            catch (Exception ex)
            {
                return View("Error", "An error occurred while deleting the employee.");
            }
        }
        #endregion


        #region SearchUsers

        [HttpGet]
        public async Task<IActionResult> SearchUsers(string searchValue)
        {
            var usersQuery = _userManager.Users.AsQueryable();

            if (!string.IsNullOrEmpty(searchValue))
            {
                usersQuery = usersQuery.Where(u =>
                    u.Email.Contains(searchValue) ||
                    u.FName.Contains(searchValue) ||
                    u.LName.Contains(searchValue));
            }

            var users = await usersQuery.ToListAsync();
            var usersVm = new List<UsersViewModel>();

            foreach (var user in users)
            {
                var roles = await _userManager.GetRolesAsync(user);
                usersVm.Add(new UsersViewModel
                {
                    Id = user.Id,
                    Email = user.Email,
                    FName = user.FName,
                    LName = user.LName,
                    Roles = roles.ToList()
                });
            }
            return PartialView("~/Views/User/Partials/_UserTablePartial.cshtml", usersVm);

        }

        #endregion

    }

}

Demo.PL/Views/Shared/_AuthLayout.cshtml
@if (!string.IsNullOrEmpty(TempData["Message"] as string))
{
    <div aria-live="polite" aria-atomic="true" class="position-fixed bottom-0 end-0 p-3" style="z-index: 1050;">
        <div class="toast show" role="alert" aria-live="assertive" aria-atomic="true">
            <div class="toast-header">
                <img src="~/img/checkmark.png" class="rounded me-2" alt="Success Icon" width="20" height="20">
                <strong class="me-auto text-primary">Success!</strong>
                <small class="text-muted">@DateTime.Now.ToString("hh:mm tt")</small>
                <button type="button" class="btn-close" data-bs-dismiss="toast" aria-label="Close"></button>
            </div>
            <div class="toast-body">
                @TempData["Message"]
            </div>
        </div>
    </div>
}


@if (TempData["Error"] is List<string> errors && errors.Any())
{


        <div class="toast position-fixed bottom-0 end-0 p-3" role="alert" aria-live="assertive" aria-atomic="true">
        <div class="toast-body">
            @foreach (var error in errors)
            {
                <li>@error</li>
            }
            <div class="mt-2 pt-2 border-top">
                <button type="button" class="btn btn-primary btn-sm">Take action</button>
                <button type="button" class="btn btn-secondary btn-sm" data-bs-dismiss="toast">Close</button>
            </div>
        </div>
    </div>


}


<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - MVC Project</title>

    <!-- Bootstrap & Styles -->
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/Demo.PL.styles.css" asp-append-version="true" />
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.7.2/css/all.min.css" integrity="sha512-Evv84Mr4kqVGRNSgIGL/F/aIDqQb7xQ2vcrdIwxfjThSH8CSR7PBEakCr51Ck+w+/U6swU2Im1vVX0SVk9ABhg==" crossorigin="anonymous" referrerpolicy="no-referrer" />
    <link href="~/css/site.css" rel="stylesheet" />

</head>
<body>
		
	<div class="section">
		<div class="container">
			<div class="row full-height justify-content-center">
				<div class="col-12 text-center align-self-center py-5">
                    <div class="section pb-5 pt-5 pt-sm-2 text-center">
                        <h6 class="mb-0 pb-3">
                            <span id="login-tab" class="tab" onclick="toggleForm('login')">
                                <a asp-action="LogIn" class="link">
                                    Log In
                                </a>
                            </span>
                            <span id="register-tab" class="tab active" onclick="toggleForm('register')">
                                <a asp-action="Register" class="link">
                                    Sign Up
                                </a>
                                
                                </span>
                        </h6>

                        <div class="card-3d-wrap mx-auto">
                            <div class="card-3d-wrapper">
                                
                               @RenderBody()
                            </div>
                        </div>
                    </div>
				</div>
			</div>
		</div>
	</div>





    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/js/site.js"></script>
    <script src="~/lib/jquery-validation/dist/jquery.validate.min.js"></script>
    <script src="~/lib/jquery-validation-unobtrusive/jquery.validate.unobtrusive.min.js"></script>
    @RenderSection("ValidationScripts", required: false)
    <script>
        $(document).ready(function () {
            $('form input, form select, form textarea').on('blur', function () {
                $(this).valid();
            });
        });

        document.addEventListener("DOMContentLoaded", function () {
            var toastEl = document.querySelector(".toast");
            if (toastEl) {
                var toast = new bootstrap.Toast(toastEl, { delay: 5000 });
                toast.show();
            }
        });


    </script>


    <script>
        document.addEventListener("DOMContentLoaded", function () {
            var toastEl = document.querySelector('.toast');
            if (toastEl) {
                var toast = new bootstrap.Toast(toastEl);
                toast.show();
            }
        });
    </script>

</body>
</html>

Demo.PL/Views/Shared/_ButtonsPartial.cshtml
@model string
<td>
    <a class="btn btn-primary" asp-action="Details" asp-route-Id="@Model">
        <i class="fas fa-eye"></i>
    </a>



    <a class="btn btn-success" asp-action="Edit" asp-route-Id="@Model">
        <i class="fas fa-edit"></i>
    </a>



    <button type="button" class="btn btn-danger" data-bs-toggle="modal" asp-route-Id="@Model" data-bs-target="#deleteModal-@Model">

        <i class="fas fa-trash"></i>
    </button>

</td>

Demo.PL/Views/Shared/_Layout.cshtml
@{

    ViewData["Title"] = "Home Page";

}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title> @ViewData["Title"]-MVC Project</title>

    <!-- Bootstrap & Styles -->

    <link href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.4.0/css/all.min.css" rel="stylesheet">
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
 <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" /> 
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.7.2/css/all.min.css" integrity="sha512-Evv84Mr4kqVGRNSgIGL/F/aIDqQb7xQ2vcrdIwxfjThSH8CSR7PBEakCr51Ck+w+/U6swU2Im1vVX0SVk9ABhg==" crossorigin="anonymous" referrerpolicy="no-referrer" />
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.7.2/css/all.min.css"
          integrity="sha512-Evv84Mr4kqVGRNSgIGL/F/aIDqQb7xQ2vcrdIwxfjThSH8CSR7PBEakCr51Ck+w+/U6swU2Im1vVX0SVk9ABhg=="
          crossorigin="anonymous" referrerpolicy="no-referrer" />

    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/css/bootstrap.min.css" rel="stylesheet">

    <style>
        body {
            margin: 0;
            font-family: 'Segoe UI', Tahoma, Geneva, Verdana, sans-serif;
            background-color: #f8f9fa;
            color: #343a40;
            line-height: 1.6;
            /* display: flex; */
            flex: 1;
        }

        /* Updated Navbar Styling */
        .navbar {
            background: linear-gradient(to right, #5c6bc0, #283593);
            box-shadow: 0 0.5rem 1rem rgba(0, 0, 0, 0.1);
            padding: 0.4rem 0;
            z-index: 100;
            position: relative;
            transition: background-color 0.3s ease;
        }

        .navbar-container {
            display: flex;
            justify-content: space-between;
            align-items: center;
            max-width: 1200px;
            margin: 0 auto;
            padding: 0 1.5rem;
        }

        .navbar-brand {
            font-size: 1.75rem;
            font-weight: 600;
            color: #fff;
            text-decoration: none;
            display: flex;
            align-items: center;
            transition: color 0.3s ease;
        }

            .navbar-brand:hover {
                color: #ffc107;
            }

            .navbar-brand svg {
                margin-right: 0.75rem;
                transition: transform 0.3s ease;
                fill: #fff;
            }

            .navbar-brand:hover svg {
                transform: rotate(15deg);
                fill: #ffc107;
            }

        .nav-tabs {
            border-bottom: none;
        }

            .nav-tabs .nav-link {
                color: #fff;
                text-decoration: none;
                padding: 0.75rem 1.25rem;
                border: none;
                border-radius: 0.25rem;
                transition: color 0.3s ease, background-color 0.3s ease;
            }

                .nav-tabs .nav-link:hover,
                .nav-tabs .nav-link:focus {
                    background-color: rgba(255, 255, 255, 0.1);
                    color: #ffc107;
                }

                .nav-tabs .nav-link.active {
                    background-color: #ffc107;
                    color: #283593;
                    border-radius: 0.25rem;
                }

                .nav-tabs .nav-link i {
                    margin-right: 0.5rem;
                }

        .navbar-toggler {
            border: none;
            background-color: transparent;
            color: #fff;
        }

            .navbar-toggler:focus {
                box-shadow: none;
            }

        /* Updated Footer Styling */
        /*    .footer {
                                    position: fixed;
                                    bottom: 0;
                                    left: 0;
                                    width: 100%;
                                    background-color: #ccc;
                                    text-align: center;
                                    padding: 10px;
                                } */

        .footer {
            background-color: #ccc;
            text-align: center;
            padding: 10px;
        }

            .footer a {
                color: #ffc107;
                text-decoration: none;
                transition: color 0.3s ease;
            }

                .footer a:hover {
                    color: #fff;
                    text-decoration: underline;
                }

        /* General Container Styling */
        .container {
            max-width: 1200px;
            margin: 0 auto;
            padding: 1.5rem;
        }

        /* Main Content Styling */
        main {
            padding: 2rem 0;
        }

        /* Responsive Styling */

    </style>
</head>
<body>
    <header>

        <nav class="navbar navbar-expand-lg">
            <div class="container">
                <a class="navbar-brand" asp-controller="Home" asp-action="Index">
                    <i class="fas fa-laptop-code"></i> MVC Project
                </a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav"
                        aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
                    <i class="fas fa-bars" style="color:#fff"></i>
                </button>
                <div class="collapse navbar-collapse justify-content-center" id="navbarNav">
                    <ul class="nav nav-tabs">
                        <li class="nav-item">
                            <a class="nav-link" aria-current="page" asp-controller="Home" asp-action="Index">
                                <i class="fas fa-home"></i> Home
                            </a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" asp-controller="Department" asp-action="Index">
                                <i class="fas fa-building"></i> Departments
                            </a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" asp-controller="Employee" asp-action="Index">
                                <i class="fa-solid fa-address-card"></i> Employees
                            </a>
                        </li>
                        @if(User.IsInRole("Admin"))
                        {
                            <li class="nav-item">
                                <a class="nav-link" asp-controller="User" asp-action="Index">
                                    <i class="fa-solid fa-users"></i> Users
                                </a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link" asp-controller="Role" asp-action="Index">
                                    <i class="fa-solid fa-pen-ruler"></i> Roles
                                </a>
                            </li>
                        }



                        <li class="nav-item">
                            <a class="nav-link" asp-controller="Account" asp-action="Logout">
                                <i class="fa-solid fa-right-from-bracket"></i>
                            </a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>

    </header>

    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="footer">
        <div>
            &copy; @DateTime.UtcNow.Year - Demo.PL | <a class="text-decoration-none" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>

    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/js/site.js"></script>
    <script src="~/lib/jquery-validation/dist/jquery.validate.min.js"></script>
    <script src="~/lib/jquery-validation-unobtrusive/jquery.validate.unobtrusive.min.js"></script>
    @await RenderSectionAsync("ValidationScripts", required: false)
    <script>
        $(document).ready(function () {
            $('form input, form select, form textarea').on('blur', function () {
                $(this).valid();

            });
        });
    </script>
    <script>
        document.addEventListener("DOMContentLoaded", function () {
            var toastEl = document.querySelector(".toast");
            var toast = new bootstrap.Toast(toastEl, { delay: 5000 }); // Auto-hide after 5 seconds
            toast.show();
        });
    </script>

</body>

</html>